import { Facility } from "./types";

// MVP段階のダミーデータです。
// 実際の施設データ（下書き調査済み・要確認）は Supabase 接続後に置き換えます。
export const facilities: Facility[] = [
  {
    id: "1",
    slug: "hanakado-cafe",
    name: "HANAKADO cafe",
    category: "cafe",
    area: "世田谷区",
    address: "東京都世田谷区尾山台（詳細住所は確認中）",
    description:
      "尾山台にある和モダンな空間の犬同伴カフェ。犬用メニューもあり、愛犬とのんびり過ごせます。",
    dogPolicy: "indoor",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: false,
    hasDogMenu: true,
    hasParking: false,
    reservationRequired: "recommended",
    businessHours: "11:00〜18:00（確認中）",
    websiteUrl: "https://hanakado.com/",
    images: [
      "https://picsum.photos/seed/hanakado1/800/600",
      "https://picsum.photos/seed/hanakado2/800/600",
    ],
  },
  {
    id: "2",
    slug: "anea-cafe-monnaka",
    name: "ANEA CAFE MONNAKA Village",
    category: "cafe",
    area: "江東区",
    address: "東京都江東区富岡2-9-11",
    description: "江東区富岡のカフェ。大型犬まで店内OKで、犬用メニューも用意されています。",
    dogPolicy: "indoor",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: true,
    hasDogMenu: true,
    hasParking: false,
    reservationRequired: "not_required",
    businessHours: "10:00〜19:00（確認中）",
    phone: "03-6458-5527",
    websiteUrl: "https://anea.jp/",
    images: [
      "https://picsum.photos/seed/anea1/800/600",
      "https://picsum.photos/seed/anea2/800/600",
    ],
  },
  {
    id: "3",
    slug: "monsoon-cafe-daikanyama",
    name: "モンスーンカフェ 代官山",
    category: "restaurant",
    area: "渋谷区",
    address: "東京都渋谷区代官山（詳細住所は確認中）",
    description:
      "代官山のアジアンダイニング。入口付近の店内席とテラス席が犬同伴OK。無料の地下駐車場あり。",
    dogPolicy: "conditional",
    indoorAllowed: true,
    terraceAllowed: true,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: true,
    hasDogMenu: false,
    hasParking: true,
    reservationRequired: "recommended",
    businessHours: "11:30〜23:00（確認中）",
    images: [
      "https://picsum.photos/seed/monsoon1/800/600",
      "https://picsum.photos/seed/monsoon2/800/600",
    ],
  },
  {
    id: "4",
    slug: "au-gamin-de-tokio-table",
    name: "AU GAMIN DE TOKIO table",
    category: "restaurant",
    area: "渋谷区",
    address: "東京都渋谷区恵比寿3-28-3 CASA PIATTO 1F",
    description: "恵比寿のレストラン。1階のみ、小型犬同伴で利用できます。",
    dogPolicy: "conditional",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: false,
    allowsLargeDog: false,
    hasDogMenu: false,
    hasParking: false,
    reservationRequired: "required",
    businessHours: "ランチ 12:00〜14:00／ディナー 17:30〜22:30",
    phone: "03-3444-4991",
    images: [
      "https://picsum.photos/seed/gamin1/800/600",
      "https://picsum.photos/seed/gamin2/800/600",
    ],
  },
  {
    id: "5",
    slug: "yoyogi-park-dogrun",
    name: "代々木公園ドッグラン",
    category: "dogrun",
    area: "渋谷区",
    address: "東京都渋谷区代々木神園町2-1",
    description:
      "都内最大級のドッグラン。犬のサイズ別にエリア分けされています。利用には事前のWEB登録が必要です。",
    dogPolicy: "conditional",
    indoorAllowed: false,
    terraceAllowed: true,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: true,
    hasDogMenu: false,
    hasParking: true,
    reservationRequired: "required",
    businessHours: "24時間（要事前登録）",
    websiteUrl: "https://www.yoyogidogrun.jp/",
    images: [
      "https://picsum.photos/seed/yoyogi1/800/600",
      "https://picsum.photos/seed/yoyogi2/800/600",
    ],
  },
  {
    id: "6",
    slug: "komazawa-olympic-park-dogrun",
    name: "駒沢オリンピック公園ドッグラン",
    category: "dogrun",
    area: "世田谷区",
    address: "東京都世田谷区駒沢公園（詳細住所は確認中）",
    description:
      "小型犬エリアと中大型犬優先エリアに分かれた登録制のドッグラン。狂犬病注射済票の登録が必要です。",
    dogPolicy: "conditional",
    indoorAllowed: false,
    terraceAllowed: true,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: true,
    hasDogMenu: false,
    hasParking: false,
    reservationRequired: "required",
    businessHours: "24時間（要事前登録）",
    phone: "03-3421-6431",
    images: [
      "https://picsum.photos/seed/komazawa1/800/600",
      "https://picsum.photos/seed/komazawa2/800/600",
    ],
  },
  {
    id: "7",
    slug: "top-dogs-fukasawa",
    name: "TOP DOGS 深沢本店",
    category: "pethotel",
    area: "世田谷区",
    address: "東京都世田谷区深沢1-1-1",
    description: "動物病院と提携するペットホテル。トリミングサロンも併設しています。",
    dogPolicy: "conditional",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: true,
    hasDogMenu: false,
    hasParking: false,
    reservationRequired: "required",
    businessHours: "平日10:00〜19:30（火休）／土日10:00〜20:00",
    phone: "03-6411-6252",
    websiteUrl: "https://topdogs.co.jp/",
    images: [
      "https://picsum.photos/seed/topdogs1/800/600",
      "https://picsum.photos/seed/topdogs2/800/600",
    ],
  },
  {
    id: "8",
    slug: "the-kennels-tokyo",
    name: "THE ケネルズ東京",
    category: "pethotel",
    area: "目黒区",
    address: "東京都目黒区（詳細住所は確認中）",
    description: "老犬ホーム機能も備えたペットホテル。全サイズの犬に対応しています。",
    dogPolicy: "conditional",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: true,
    allowsLargeDog: true,
    hasDogMenu: false,
    hasParking: false,
    reservationRequired: "required",
    businessHours: "確認中",
    phone: "03-6451-0028",
    websiteUrl: "https://the-kennels.tokyo/",
    images: [
      "https://picsum.photos/seed/kennels1/800/600",
      "https://picsum.photos/seed/kennels2/800/600",
    ],
  },
  {
    id: "9",
    slug: "dog-salon-vid-omotesando",
    name: "DOG SALON V.I.D. OMOTESANDO",
    category: "petsalon",
    area: "渋谷区",
    address: "東京都渋谷区表参道エリア（詳細住所は確認中）",
    description: "トイプードルなど、小型犬を中心に施術するトリミングサロン。完全予約制です。",
    dogPolicy: "conditional",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: false,
    allowsLargeDog: false,
    hasDogMenu: false,
    hasParking: false,
    reservationRequired: "required",
    businessHours: "確認中",
    images: [
      "https://picsum.photos/seed/vid1/800/600",
      "https://picsum.photos/seed/vid2/800/600",
    ],
  },
  {
    id: "10",
    slug: "m-neige",
    name: "M*neige（エムネイジュ）",
    category: "petsalon",
    area: "世田谷区",
    address: "東京都世田谷区駒沢2-40-8 井上ビル1F",
    description: "小型犬専門のトリミングサロン。隣にコインパーキングがあります。",
    dogPolicy: "conditional",
    indoorAllowed: true,
    terraceAllowed: false,
    allowsSmallDog: true,
    allowsMediumDog: false,
    allowsLargeDog: false,
    hasDogMenu: false,
    hasParking: true,
    reservationRequired: "required",
    businessHours: "10:00〜19:00",
    websiteUrl: "http://m-neige.com/",
    images: [
      "https://picsum.photos/seed/mneige1/800/600",
      "https://picsum.photos/seed/mneige2/800/600",
    ],
  },
];

export const AREAS = Array.from(new Set(facilities.map((f) => f.area)));

export function getFacilityBySlug(slug: string): Facility | undefined {
  return facilities.find((f) => f.slug === slug);
}
